### ISSUE TITLE
slash character prevents correct result

### ISSUE THREAD

**Issue by guenterh** [swissbib/searchconf#53] opened 2018-09-25 16:18 UTC
a query like this
Klassifikationen in Bibliotheken : Theorie - Anwendung - Nutzen / Heidrun Alex, Guido Bee und Ulrike Junger

returns 0 hits.
Without the slash character the correct result is returned
Klassifikationen in Bibliotheken : Theorie - Anwendung - Nutzen  Heidrun Alex, Guido Bee und Ulrike Junger

In Solr4 the / character didn't suppress hits
Shouldn't be a blocker for Migration to SOLR7 but part of improving search quality

**Comment by liowalter** [comment] 2018-11-19 18:12
duplicate of https://github.com/swissbib/vufind/issues/664

**Closed by liowalter** 2018-11-19 18:12 UTC
Labels: bug, improveSearchQuality, solr7_infrastructure
